### ISSUE TITLE
Make loading effect on company select dropdown

### ISSUE THREAD

**Issue by NicolajNiels1** [Kodeworks/liquidator#123]
I suggest that we make a spinning wheel  or some kind of loading effect when clicking on the dropdown list for selecting company, as long as not all companies are fetched on app mounting.

I believe we induce less thinking (hence struggle) to the user if the application doesn't tell him/her specifically in the list of companies which are loaded and not.

_Originally posted by @NicolajNiels1 in https://github.com/Kodeworks/liquidator-frontend/pull/122/review_comment/create_

**Comment by FredrikAugust** [comment]
> [...] as long as not all companies are fetched on app mounting

All companies are fetched on app mount, and a text displaying "Loading company..." is shown the milliseconds the company is being loaded.
