### ISSUE TITLE
Add and revoke company access privileges

### ISSUE THREAD

**Issue by KaizerTilt** [Kodeworks/liquidator#132]
**As a** company owner **I want** add and revoke access privileges for other users to a company that I own **so that** I can manage which users can see and edit data for my company.

### Acceptance Criteria

1.When I add privileges for a user which does not already have access to my company:
   - The user should have access to the company.
   - The user should be notified about the updated access to the company.
 
2. When I revoke privileges for a user which have access to my company:
   - The user should no longer have access to view or edit company data.

**Comment by FredrikAugust** [comment]
This requires back-end work. As of now, you can add and remove users, as well as control their permissions from the front-end.
