### ISSUE TITLE
[Story] Create a Company account

### ISSUE THREAD

**Issue by KaizerTilt** [Kodeworks/liquidator#134]
**As a** user,
**I want** to create a company account,
**so that** I can start to manage cash flows and liquidated assets of my company.

### Acceptance Criteria

1. If I create a new Company
1. The company should be available to select in the application,
1. and I should have the role of 'owner' of the new company.

Also, there are some other constraints:
1. The name of the Company account does not need to be unique.
1. The length of company name should be between 3 and 33 characters.
	1. If I write an invalid company name (too short/long), I should be prompted with an error message that tells me what I did wrong.

### Resources:

* Mockups: _There are none yet_

### Notes
_Write some complementary notes_

**Comment by FredrikAugust** [comment]
This was set to 50 in the backend, fixed.
