### ISSUE TITLE
Create, update and delete single (non-recurring) transaction for a company

### ISSUE THREAD

**Issue by KaizerTilt** [Kodeworks/liquidator#135]
**As a** user or owner **I want** to create, update and delete transactions for a company which I'm authorized for **so that** the transactions is reflected in future calculations of liquidity.

### Acceptance Criteria

1. When I try to register a new single transaction with valid inputs:
   - The transaction should be saved for the company.
   - The transaction should be reflected in future calculations of liquidity.

2. When I try to update a single transaction with valid inputs:
   - The transaction should be updated with the new data and the change should be reflected in future calculations of liquidity.

3. When I try to delete a single valid transaction:
   - The transaction should be removed and the deletion should be reflected in future calculations of liquidity.

**Comment by NicolajNiels1** [comment]
I'm breaking this Epic down to smaller user stories.
