### ISSUE TITLE
Create, update and delete a recurring transaction for a company

### ISSUE THREAD

**Issue by KaizerTilt** [Kodeworks/liquidator#136]
**As a** user or owner **I want** to create, update and delete recurring transactions for a company which I'm authorized for **so that** the transactions are reflected in future calculations of liquidity.

### Acceptance Criteria

1. When I try to register a new recurring transaction with valid inputs:
   - The transaction should be saved for the company.
   - The transaction should be reflected in future calculations of liquidity.

2. When I try to update a recurring transaction with valid inputs:
   - The transaction should be updated with the new data 
   - The change should be reflected in future calculations of liquidity.

3. When I try to delete a recurring valid transaction:
   - The transaction should be removed
   - The deletion should be reflected in future calculations of liquidity.

### Stories
* #139 
* #140 
* #141

**Comment by NicolajNiels1** [comment]
This seems like an Epic to me.
I'll break this down into smaller user stories.

**Comment by NicolajNiels1** [comment]
This is related to discussion in Kodeworks/liquidator-backend#48
