### ISSUE TITLE
[Story] Delete a single occurrence of  a recurring transaction

### ISSUE THREAD

**Issue by NicolajNiels1** [Kodeworks/liquidator#140]
👤 As a user,
🙏 I want to delete a single occurrence of a recurring transaction,
🎯 so that the liquidity calculation reflects that a transaction doesn't happen for a specific instance of a period (i.e. week/month).

🏔 **Epic:** #136

### ❗️ 	Acceptance Criteria
1. If I delete an occurrence of a recurring transaction from the list of transactions
	1. It should result in the removal of the transaction in question from the list. 
	1. The liquidity calculation should reflect this.

Other constraints:
* Depends on #139 
* I should not be able to delete a recurring transaction from a company account I'm not part of

### Resources
_Add resources_
* Mockup: _Add link to Figma_

### Notes
_Add complementary notes here_
* **This story must not be confused with the user story of deleting a recurring transaction. See #141**

**Comment by FredrikAugust** [comment]
This is implemented as you can override a recurring transaction entry, and set the value to 0.
