### ISSUE TITLE
[Story] Delete a transaction entry

### ISSUE THREAD

**Issue by NicolajNiels1** [Kodeworks/liquidator#144]
👤 As a | 🙏 I want | 🎯 so that
:---: | :---: | :---
user  | to delete a transaction entry | it will not be a part of the liquidity calculation anymore.

🏔 **Epic:** #135 

### ✅ 	Acceptance Criteria

1. If I delete a transaction
	1. It should be gone 🙌 	

Other constraints:
* I can only delete a transaction for a company account I am part of
* Likelihood of accidental deletion should be minimized... somehow 🤷‍♂ 	

### Resources

* Mockups: <span><img src="https://cdn.worldvectorlogo.com/logos/figma-1.svg" alt="figma logo" height="24"/></span> _Add link to Figma_

### Notes
* For definition for recurring transactions, see #136 

### Tasks
- [ ] _Add tasks here_ (link to issue if any)

**Comment by FredrikAugust** [comment]
Ref #187 for accidental deletion security.
