### ISSUE TITLE
[Story] See Account Overview

### ISSUE THREAD

**Issue by NicolajNiels1** [Kodeworks/liquidator#146]
👤 **As a** user
🙏 **I want** see an overview of incomes and expenses in my company account,
🎯 **so that** I better can understand the cash flows of my company.

[
🏔 **Epic:** [Link to related Epic if any]
]

### Acceptance Criteria :+1: / :-1:

1. If I navigate to the "Account Overview" page of the application
	1. I should see an account overview as a list of transactions

Other constraints:
1. History is not important to me, only future movements. Because of this I want the application to first and foremost show med transactions happening in the future. History should be optional.

### Resources 🍄

* Mockups: [Here goes a URL to or the name of the mockup(s) in Figma];
* Testing URL: [Here goes a URL to the testing branch];
* Staging URL: [Here goes a URL to the feature on staging];

### Notes 📝

[
Some complementary notes if necessary:

* > Here goes a quote from an email
* Here goes whatever useful information can exist..
]

### Tasks :white_check_mark:
- [ ] _Add tasks here_

**Comment by FredrikAugust** [comment]
As it is sorted from newest to oldest, I believe this is fixed by the transactions page.
