### ISSUE TITLE
Make it possible to use Liquidator from liquidator.kodeworks.nl

### ISSUE THREAD

**Issue by flyrev** [Kodeworks/liquidator#156]
To make it easier to test Liquidator for those who are not active developers on Liquidator, there should be a hosted version. We have the domain `liquidator.kodeworks.nl` reserved for this.

There is already an active pull request on this: https://github.com/Kodeworks/liquidator-frontend/pull/149

**Comment by kalkins** [comment]
The prod build has been fixed in #149, but we don't have CD yet, so the server has to be updated manually. Should this issue be closed now, or do we wait until we have CD?

**Comment by flyrev** [comment]
We can close this, and re-visit CD. There are many options here. I would suggest publishing Docker images directly to Docker Hub on merge to `master`, and use those images directly, but there are a lot of options here. :)
