### ISSUE TITLE
Automatically create a new company for newly registered users

### ISSUE THREAD

**Issue by flyrev** [Kodeworks/liquidator#165]
The user has to create at least one company to be able to do anything useful. One should be created automatically when signing up.

**Comment by FredrikAugust** [comment]
For a lot of users, they will not create their own company, but rather join one that already exists, and thus I do not see why we should automatically create one for them. But this is something that can be discussed.

Paging @NicolajNiels1

**Comment by NicolajNiels1** [comment]
Related to #172

**Comment by NicolajNiels1** [comment]
> For a lot of users, they will not create their own company, but rather join one that already exists, and thus I do not see why we should automatically create one for them. But this is something that can be discussed.

I comply with the product owner, and do not wish to enforce my opinions on this matter 😄
Feel free to discuss!

**Comment by flyrev** [comment]
@FredrikAugust : currently, our target demographic is accountants. :)

At some point, some company has to be created. So a simple and easy thing to do now is to simply have it be created at the same time as the user is.
