### ISSUE TITLE
On the Projections page, group transactions by month

### ISSUE THREAD

**Issue by flyrev** [Kodeworks/liquidator#167]
Currently all transactions are shown in the same table, with no grouping.

**Comment by KaizerTilt** [comment]
Separate tables for each month stacked vertically or an empty row separating months within the same table are the two options that comes first to mind. Which one would you prefer @flyrev?

**Comment by flyrev** [comment]
Let's do one table per month, and keep column widths fixed (with CSS grid and `fr` units, for example) so that everything still will be aligned perfectly.
