### ISSUE TITLE
[Story] Sign up as new user

### ISSUE THREAD

**Issue by NicolajNiels1** [Kodeworks/liquidator#172]
👤 **As a** user
🙏 **I want** to sign up/register on Liquidator
🎯 **so that** I can start using this awesome application

### Acceptance Criteria :+1: / :-1:
1. If I Sign up
1. A company account should be available to me the first time i log in

### Tasks :white_check_mark:
- [x] #35 Write form validation in frontend 
- [x] #165 Automatically create company for newly registered users

**Comment by FredrikAugust** [comment]
What should the company be called? Should we perhaps have a multiple-step registration, where you're prompted to create a new company when signing in for the first time?

**Comment by NicolajNiels1** [comment]
> What should the company be called? Should we perhaps have a multiple-step registration, where you're prompted to create a new company when signing in for the first time?

That sound like a good idea, and a natural extension. For now I'm going to start looking at the backend part. My plan is to just create a company called 'My Company', then in the frontend application we can just fetch any company related to a user. 🙂

**Comment by FredrikAugust** [comment]
A problem here might be that every company needs to be registered with a name and `org_nr`, of which the latter has a unique constraint in the DB, so we need to come up with a clever way to figure out what we could set that to.

The company name could just be `<name>s company`.
