### ISSUE TITLE
[Story] Add confirmation dialog to "Delete company?" to avoid accidental company deletions

### ISSUE THREAD

**Issue by HakonHesselberg** [Kodeworks/liquidator#187]
👤 **As a** user
🙏 **I want** a confirmation dialog when attempting to delete a company
🎯 **so that** so that I don't delete a company by accident

### Acceptance Criteria :+1: / :-1:
I am no longer able to delete a company with a single click.

If a user clicks **Delete company?** they are prompted with a dialog box asking if they are sure they want to delete the company, and are informed of the consequences should they do so (loss of all current data etc..)

**Comment by FredrikAugust** [comment]
Fixed by #194 .
