### ISSUE TITLE
When no transactions exist the dashboard graph shows all dates as 01/01-'70

### ISSUE THREAD

**Issue by HakonHesselberg** [Kodeworks/liquidator#189]
**Describe the bug**
When no transactions exist the dashboard graph shows all dates as 01/01-'70. This can be confusing for new users.

**To Reproduce**
1. Either create a new user with no transactions added or delete all transactions

**Expected behavior**
More recent dates, for instance the current date.

**Screenshots**
![image](https://user-images.githubusercontent.com/1553016/68845055-19406600-06cb-11ea-8f3c-f59b204eb051.png)

**Comment by FredrikAugust** [comment]
I don't think this is worth spending a lot of time on, as most people will have data in their user, but if someone wants to perhaps hide the entire page if you don't have any companies, that could be done.
