### ISSUE TITLE
Transaction - It should not be possible to add non-positive transactions

### ISSUE THREAD

**Issue by HakonHesselberg** [Kodeworks/liquidator#205]
**Describe the bug**
Is is possible to add negative or zero income/expense when adding a transaction

**To Reproduce**
1. Go to **Transactions**
2. Click on **Add new transaction**
3. Fill in form with a negative or 0 amount.
4. Click **Create new transaction**

**Expected behavior**
The user is not allowed to input negative values.

**Screenshots**
Negative expense
![image](https://user-images.githubusercontent.com/1553016/69546556-42e37200-0f94-11ea-886b-5886bb56a301.png)

0 values
![image](https://user-images.githubusercontent.com/1553016/69546589-51ca2480-0f94-11ea-8ee5-c5f3e67d8cf6.png)

**Comment by FredrikAugust** [comment]
Should also check whether this is implemented on the backend.
