### ISSUE TITLE
Projections table break with long descriptions

### ISSUE THREAD

**Issue by HakonHesselberg** [Kodeworks/liquidator#214]
**Describe the bug**
![image](https://user-images.githubusercontent.com/1553016/70513132-4f89cd80-1b31-11ea-9a13-85db44ce28f4.png)

**Comment by FredrikAugust** [comment]
Wasn't this fixed by your recent PR?

**Comment by FredrikAugust** [comment]
Oh sorry, that was for the transactions page. Maybe it would be wise to implement the same word-break functionality here?

**Comment by HakonHesselberg** [comment]
The solution for the transaction page will have to be implemented a bit differently for the projections page, as they don't calculate width of elements the same way (as seen in the picture, the width changes when you have longer text etc.)

**Comment by erikskaar** [comment]
If it is acceptable to break long words to preserve the structure then adding a simple `word-break: break-word;` to the p element will suffice.

![image](https://user-images.githubusercontent.com/43439578/72418860-f50d0e00-377b-11ea-97b6-22f216f4c5c6.png)
